#!/usr/bin/env python
# -*- coding: UTF8 -*-
#
# This file is part of simpserial.
#
# simpserial - A very simple tool to get data from serial ports
# Copyright (c) 2009 Fabian Affolter <fabian@bernewireless.net>
#
# simpserial is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
# 
# simpserial is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""sympserial"""

__author__    = "Fabian Affolter <fabian@bernewireless.net>"
__version__   = "0.0.1"
__date__      = "2009-08-14"
__copyright__ = "Copyright (c) 2009 %s. All rights reserved." % __author__
__licence__   = "GPLv3+"

import sys,os
from optparse import OptionParser

import locale
import gettext

# gettext variables for translations
APP = 'simpserial'
DIR = '/usr/share/locale/'

def main(argv=None):
    gettext.textdomain( APP )
    gettext.install( APP )
    
    if argv is None:
        argv = sys.argv

    parser = OptionParser(usage="usage: %%prog [options] arg1 arg2\n\n%s" %__doc__,
                          version = "%%prog %s %s" %(__version__, __date__))

    parser.add_option("-v", "--verbose",
                      action="store_true", dest="verbose", default=False,
                      help=_("Be more verbose"))

    parser.add_option("--debug",
                      action="store_true", dest="debug", default=False,
                      help=_("Run local version in current directory"))
    
    (options, args) = parser.parse_args(argv)

    if options.verbose:
        print "Options: " + str(options)
        print "Arguments: " + str(args)

    if options.debug:
        sys.path = ['./src/','../src/'] + sys.path

    # Default run GUI
    from simpserial import pysms
    import gtk.glade
        
    if options.debug:
    	pysms.glade_dir = './data'
        pysms.icon_dir  = './data/simpserial.png'
            
    simpserial.main( __version__ )

if __name__ == "__main__":
    sys.exit(main())
